### ISSUE TITLE
No longer working with modern versions of ARMIPS, blz and ndstools

### ISSUE THREAD

**Issue by extherian** [StraDaMa/Legend-of-Zelda-Phantom-Hourglass-D-Pad-Patch#3]
I obtained these dependencies from [here](https://github.com/Kingcom/armips), [here ](https://github.com/PeterLemon/Nintendo_DS_Compressors)and [here](https://wii.leseratte10.de/devkitPro/other-stuff/ndstool/). However, putting an EU copy of Phantom Hourglass as "input.nds" in the input folder and running compile.bat produces a ROM that is unusable, as it hangs at a white screen when loaded in melonDS. Input.nds is my own legally dumped copy of the game, so it's not that I am using a bad dump. I have uploaded a zip file with the dependencies I am using. 

[dependencies.zip](https://github.com/user-attachments/files/16644603/dependencies.zip)

I admit that I do not know for sure if it's the dependencies that are at fault, but compile.bat gives me no useful error messages to troubleshoot and appears to run successfully, so I am at a loss as to what to do.

**Comment by Dylouwu** [comment]
Hi, thanks for the amazing work, but just wanted to give a headsup that this issue is still active to this day, rendering the patch ineffective for the EU copy of Phantom Hourglass.

**Comment by StraDaMa** [comment]
This issue only affects the blz from that github repo. If you download blz from the link provided in the readme the scripts work as expected.  There doesnt seem to be any difference in the actual compression from the one in that github repo and the romhacking.net

If you insist on using the one from the repo you can modify the script as decribed in this issue
https://github.com/StraDaMa/Legend-of-Zelda-Spirit-Tracks-D-Pad-Patch/issues/3#issuecomment-2294933544

**Comment by Dylouwu** [comment]
Alright, thanks for the clear explanation and your time I appreciate it.
